## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
import pandas as pd
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
#q1-1
data = pd.DataFrame(data,columns=["name","job","family_size","num_cars"])
print(data)

print() #seperate answers for aesthetic purposes

#q1-2
q2 = data[((data.job=="psychologist") | (data.job=="teacher")) & (data.num_cars > data.family_size)]
#first select psychologist or teacher, then select ones who have more cars than family size
print(q2)

print() #seperate answers for aesthetic purposes

#q1-3
q3 = data[(data.family_size <= 2) & (data.num_cars >= 1)]
print(q3)

print() #seperate answers for aesthetic purposes

#q1-4
num_unique_jobs = len(data["job"].unique())
print("The number of unique jobs in this dataset is", num_unique_jobs)

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

The number of unique jobs in this dataset is 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
#create dataframe
frame = pd.DataFrame(columns=["fruit","weights"]) #create a shell dataframe
frame["fruit"] = fruit      #assign fruits to fruit column
frame["weights"] = weights  #assign weights to weights column
print(frame, "\n")

apple = frame[frame.fruit == "apple"] #df for just apples
meanapple = pd.DataFrame.mean(apple["weights"])  #mean weight of apples

carrot = frame[frame.fruit == "carrot"] #df for just carrots
meancarrot = pd.DataFrame.mean(carrot["weights"])  #mean weight of carrots

banana = frame[frame.fruit == "banana"] #df for just bananas
meanbanana = pd.DataFrame.mean(banana["weights"])  #mean weight of bananas

print("The mean weight of apples:", meanapple)
print("The mean weight of carrots:", meancarrot)
print("The mean weight of bananas:", meanbanana)

    fruit  weights
0   apple      1.0
1  banana      2.0
2  banana      3.0
3   apple      4.0
4  banana      5.0
5  banana      6.0
6   apple      7.0
7  banana      8.0
8  carrot      9.0
9  banana     10.0 

The mean weight of apples: 4.0
The mean weight of carrots: 9.0
The mean weight of bananas: 5.666666666666667


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
#q3-1
sorted = np.sort(course_name)           #sort the courses
sorted_index = np.array([],dtype=np.int) #create empty array for the indices of sorted elements
for i in sorted:            #loop through each element in sorted courses
  sorted_index = np.append(sorted_index,np.where(course_name==i)) 
  #use where to get index of the sorted element via the orignal array and append to the sorted_index
print(sorted_index)

print() #seperate answers for aesthetic purposes

#q3-2
check = np.char.startswith(course_name,"P") #checks which element starts with "P" and returns array of Booleans
p = course_name[check]  #store the elements that begin with p into a new array
print(p[0],"and",p[1], "begin with the letter \"P\"")

[1 3 0 2 4]

Python and PHP begin with the letter "P"


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#q4-1
rev = np.flip(student_id)     #reverse the array and save to variable rev
print(student_id)
print(rev)

print() #seperate answers for aesthetic purposes

#q4-2
sorted = np.sort(student_id)  #sort the array in ascending order and save to variable sorted
large = (sorted[-3:])         #use -index to get the last 3 numbers and save to variable large
print(large)            

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]

[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
arr = np.arange(0,101)  #create array of int from 0 to 100
mult35 = arr[np.logical_or(arr%3==0,arr%5==0)] #use or to only keep multiples of 3 or 5
print(np.sum(mult35)) #sum all of the multiples of 3 or 5


2418


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#q6.1
arr[:,[1,2]] = arr[:,[2,1]] #select column 1 and 2 and replace with the reverse of column 1 and 2
print(arr)

print() #seperate answers for aesthetic purposes

#q6.2
arr[[0,1],:] = arr[[1,0],:] #select row 0 and 1 and replace with the reverse of row 0 and 1
print(arr)


[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
